Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using NNShop.Data;
using NNShop.ViewModels;
using NNShop.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;


namespace NNShop.Controllers
{
    public class CartController : Controller
    {
        private readonly NnshopContext db;

        public CartController(NnshopContext context)
        {
            db = context;
        }

        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(MySetting.CART_KEY) ?? new List<CartItem>();
        [Authorize]
        public IActionResult Index()
        {
            return View(Cart);
        }
        public IActionResult AddToCart(string id, int quantity = 1)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item == null)
            {
                var hangHoa = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
                if (hangHoa == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return Redirect("/404");
                }
                item = new CartItem
                {
                    MaHh = hangHoa.MaHh,
                    TenHH = hangHoa.TenHh,
                    DonGia = hangHoa.DonGia ?? 0,
                    Hinh = hangHoa.Hinh ?? string.Empty,
                    SoLuong = quantity,
                    GiamGia = hangHoa.GiamGia
                };
                gioHang.Add(item);
            }
            else
            {
                item.SoLuong += quantity;
            }
            HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveCart(string id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                gioHang.Remove(item);
                HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Tang(string id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                item.SoLuong += 1;
                HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Giam(string id)
        {
            var gioHang = Cart;
            var item = gioHang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                item.SoLuong -= 1;
                HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            if (Cart.Count == 0)
            {
                return Redirect("/HangHoa");
            }

            return View(Cart);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutVM model)
        {
            if (ModelState.IsValid)
            {
                var khachhang = new KhachHang();
                var nhanvien = new NhanVien();
                var staffId = int.Parse(HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_STAFFID).Value);
                if (model.giongnhannvien)
                {
                    nhanvien = db.NhanViens.SingleOrDefault(nv => nv.MaNv == staffId);
                }
                var hoadon = new DonHang
                {
                    MaNv = staffId,
                    MaKh = model.MaKH,
                    HoTen = model.HoTen ?? khachhang.HoTen,
                    Diachi = model.DiaChi ?? khachhang.DiaChi,
                    NgayDat = DateOnly.FromDateTime(DateTime.Now),
                    NgayGiao = DateOnly.FromDateTime(DateTime.Now),
                    VanChuyen = "Nhận Tại quầy",
                    MaTt = 1,
                    GhiChu = model.GhiChu,
                    TongTien = Cart.Sum(item => (item.DonGia - item.GiamGia) * item.SoLuong)
                };

                db.Database.BeginTransaction();
                try
                {
                    db.AddRange(hoadon);
                    await db.SaveChangesAsync();

                    var cthds = new List<ChiTietDonHang>();
                    foreach (var item in Cart)
                    {
                        // Lấy sản phẩm từ cơ sở dữ liệu
                        var hangHoa = db.HangHoas.SingleOrDefault(hh => hh.MaHh == item.MaHh);
                        if (hangHoa == null || hangHoa.SoLuong < item.SoLuong)
                        {
                            throw new Exception($"Không đủ số lượng hàng hóa: {item.TenHH}");
                        }

                        // Giảm số lượng sản phẩm
                        hangHoa.SoLuong -= item.SoLuong;
                        // Tính đơn giá sau giảm giá
                        var donGiaSauGiam = item.DonGia - item.GiamGia;

                        // Đảm bảo đơn giá không âm
                        if (donGiaSauGiam < 0)
                        {
                            throw new Exception($"Giảm giá không hợp lệ cho sản phẩm: {item.TenHH}");
                        }

                        // Tạo chi tiết đơn hàng
                        cthds.Add(new ChiTietDonHang
                        {
                            MaDh = hoadon.MaDh,
                            SoLuong = item.SoLuong,
                            DonGia = item.DonGia,
                            MaHh = item.MaHh,
                            GiamGia = (int?)Math.Round(item.GiamGia) * item.SoLuong,
                            TongTien = donGiaSauGiam * item.SoLuong

                        });
                    }
                    db.UpdateRange(db.HangHoas);
                    db.AddRange(cthds);
                    await db.SaveChangesAsync();

                    db.Database.CommitTransaction();

                    HttpContext.Session.Set<List<CartItem>>(MySetting.CART_KEY, new List<CartItem>());

                    return View("Success");

                }
                catch
                {
                    if (db.Database.CurrentTransaction != null)
                    {
                        db.Database.RollbackTransaction();
                    }

                    return View("");
                }
            }

            return View(Cart);
        }
    }
}

Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NNShop.Data;
using NNShop.ViewModels;
namespace NNShop.Controllers
{
    [Authorize]
    public class DonHangController : Controller
    {
        private readonly NnshopContext _context;

        public DonHangController(NnshopContext context)
        {
            _context = context;
        }

        // GET: DonHang
        public async Task<IActionResult> Index()
        {
            var nnshopContext = _context.DonHangs.Include(d => d.MaKhNavigation).Include(d => d.MaNvNavigation).Include(d => d.MaTtNavigation);
            return View(await nnshopContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Lấy thông tin đơn hàng và chi tiết đơn hàng liên quan
            var donHang = await _context.DonHangs
                .Include(d => d.ChiTietDonHangs) // Bao gồm chi tiết đơn hàng
                .ThenInclude(ct => ct.MaHhNavigation) // Bao gồm thông tin hàng hóa
                .Include(d => d.MaKhNavigation) // Bao gồm thông tin khách hàng
                .Include(d => d.MaNvNavigation) // Bao gồm thông tin nhân viên
                .Include(d => d.MaTtNavigation) // Bao gồm thông tin trạng thái
                .FirstOrDefaultAsync(d => d.MaDh == id);

            if (donHang == null)
            {
                return NotFound();
            }

            // Tính tổng tiền chi tiết đơn hàng
            double? tongThanhTien = donHang.ChiTietDonHangs.Sum(ct => ct.TongTien);

            // Gửi tổng tiền qua ViewData
            ViewData["TongThanhTien"] = tongThanhTien;

            return View(donHang);
        }



        // GET: DonHang/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var donHang = await _context.DonHangs.FindAsync(id);
            if (donHang == null)
            {
                return NotFound();
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", donHang.MaKh);
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv", donHang.MaNv);
            ViewData["MaTt"] = new SelectList(_context.TrangThais, "MaTt", "MaTt", donHang.MaTt);
            return View(donHang);
        }

        // POST: DonHang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaDh,MaKh,NgayDat,NgayGiao,HoTen,Diachi,MaNv,GhiChu,VanChuyen,TongTien,MaTt")] DonHang donHang)
        {
            if (id != donHang.MaDh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(donHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DonHangExists(donHang.MaDh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.KhachHangs, "MaKh", "MaKh", donHang.MaKh);
            ViewData["MaNv"] = new SelectList(_context.NhanViens, "MaNv", "MaNv", donHang.MaNv);
            ViewData["MaTt"] = new SelectList(_context.TrangThais, "MaTt", "MaTt", donHang.MaTt);
            return View(donHang);
        }

        // GET: DonHang/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var donHang = await _context.DonHangs
                .Include(d => d.MaKhNavigation)
                .Include(d => d.MaNvNavigation)
                .Include(d => d.MaTtNavigation)
                .FirstOrDefaultAsync(m => m.MaDh == id);
            if (donHang == null)
            {
                return NotFound();
            }

            return View(donHang);
        }

        // POST: DonHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var donHang = await _context.DonHangs.FindAsync(id);
            if (donHang != null)
            {
                _context.DonHangs.Remove(donHang);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DonHangExists(int id)
        {
            return _context.DonHangs.Any(e => e.MaDh == id);
        }


        public async Task<IActionResult> ThongKeSanPham()
        {
            var thongKeSanPham = await _context.ChiTietDonHangs
            .GroupBy(ct => ct.MaHh)
            .Select(g => new
            {
                MaHh = g.Key,
                TenHh = g.FirstOrDefault().MaHhNavigation.TenHh,
                SoLuongBan = g.Sum(ct => ct.SoLuong),
                TongDoanhThu = g.Sum(ct => ct.TongTien)
            })
                .OrderByDescending(r => r.SoLuongBan)
                .ToListAsync();

            return View(thongKeSanPham);
        }

        // Thống kê doanh thu theo ngày
        public async Task<IActionResult> ThongKeDoanhThuTheoNgay()
        {
            var doanhThuTheoNgay = await _context.DonHangs
                .GroupBy(d => d.NgayDat)
                .Select(g => new ThongKeViewModel
                {
                    // Kiểm tra null trước khi chuyển đổi
                    Ngay = g.Key.HasValue ? g.Key.Value.ToDateTime(TimeOnly.MinValue) : (DateTime?)null,
                    TongDoanhThu = g.Sum(d => d.TongTien) ?? 0
                })
                .OrderBy(r => r.Ngay)
                .ToListAsync();

            return View("ThongKeIndex", doanhThuTheoNgay);
        }



        // Thống kê doanh thu theo tháng
        public async Task<IActionResult> ThongKeDoanhThuTheoThang()
        {
            var doanhThuTheoThang = await _context.DonHangs
                .Where(d => d.NgayDat.HasValue)
                .GroupBy(d => new { d.NgayDat.Value.Year, d.NgayDat.Value.Month })
                .Select(g => new ThongKeViewModel
                {
                    Nam = g.Key.Year,
                    Thang = g.Key.Month,
                    TongDoanhThu = g.Sum(d => d.TongTien) ?? 0
                })
                .OrderBy(r => r.Nam).ThenBy(r => r.Thang)
                .ToListAsync();

            return View("ThongKeIndex", doanhThuTheoThang);
        }

        // Thống kê doanh thu theo năm
        public async Task<IActionResult> ThongKeDoanhThuTheoNam()
        {
            var doanhThuTheoNam = await _context.DonHangs
                .Where(d => d.NgayDat.HasValue)
                .GroupBy(d => d.NgayDat.Value.Year)
                .Select(g => new ThongKeViewModel
                {
                    Nam = g.Key,
                    TongDoanhThu = g.Sum(d => d.TongTien) ?? 0
                })
                .OrderBy(r => r.Nam)
                .ToListAsync();

            return View("ThongKeIndex", doanhThuTheoNam);
        }

        // Trang Thống kê
        public IActionResult ThongKeIndex()
        {
            return View();
        }
    }






}

ViewComponents/MenuLoaiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NNShop.Data;
using NNShop.ViewModels;

namespace NNShop.ViewComponents
{
    public class MenuLoaiViewComponent : ViewComponent
    {
        private readonly NnshopContext db;

        public MenuLoaiViewComponent(NnshopContext context) => db = context;

        public IViewComponentResult Invoke()
        {
            var data = db.LoaiHhs.Select(lo => new MenuLoaiVM
            {
                MaLoai = lo.MaLoaiHh,
                TenLoai = lo.TenLoaiHh,
                SoLuong = lo.HangHoas.Count
            }).OrderBy(p => p.TenLoai);

            return View(data);
        }
    }
}

Views/Shared/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="#">
                        <h1 class="text-primary mb-0">Nice Nice Shop</h1>
                        <p class="text-secondary mb-0">Cửa Hàng Tạp Hóa</p>
                    </a>
                </div>
                @* <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                        <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                    </div>
                </div> *@
                @*  <div class="col-lg-3">
                     <div class="d-flex justify-content-end pt-3">
                         <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                         <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                         <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                         <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                     </div>
                 </div> *@
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Giới Thiệu Cửa Hàng</h4>
                    <p class="mb-5">
                        Cửa hàng tạp hóa Nice Nice Shop là điểm đến lý tưởng cho mọi gia đình với các sản phẩm tiêu dùng thiết yếu, từ thực phẩm, đồ uống, đến các mặt hàng gia dụng, chăm sóc sức khỏe. Chúng tôi cam kết cung cấp những sản phẩm chất lượng, nguồn gốc rõ ràng, giá cả hợp lý để phục vụ nhu cầu hàng ngày của khách hàng. Với không gian mua sắm sạch sẽ, thoải mái cùng đội ngũ nhân viên tận tình, cửa hàng tạp hóa Nice Nice Shop luôn mong muốn mang đến sự hài lòng và tiện lợi tối đa cho bạn. 
                        Hãy đến và trải nghiệm mua sắm tuyệt vời cùng chúng tôi!
                    </p>
                    @* <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a> *@
                </div>
            </div>
            @* <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Shop Info</h4>
                    <a class="btn-link" href="">About Us</a>
                    <a class="btn-link" href="">Contact Us</a>
                    <a class="btn-link" href="">Privacy Policy</a>
                    <a class="btn-link" href="">Terms & Condition</a>
                    <a class="btn-link" href="">Return Policy</a>
                    <a class="btn-link" href="">FAQs & Help</a>
                </div>
            </div> *@
           @*  <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Account</h4>
                    <a class="btn-link" href="">My Account</a>
                    <a class="btn-link" href="">Shop details</a>
                    <a class="btn-link" href="">Shopping Cart</a>
                    <a class="btn-link" href="">Wishlist</a>
                    <a class="btn-link" href="">Order History</a>
                    <a class="btn-link" href="">International Orders</a>
                </div>
            </div> *@
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Liên Hệ</h4>
                    <p>Địa Chỉ: 256 Nguyễn Văn Cừ, An Hòa, Cần Thơ</p>
                    <p>Email Của Chúng tôi:</p>
                    <p class="mb-2">nnthicntt2211029@student.ctuet.edu.vn</p>
                    <p class="mb-2">nkphungcntt2211048@student.ctuet.edu.vn</p>
                    <p class="mb-2">tttkieucntt2211013@student.ctuet.edu.vn</p>
                    <p>Số điện thoại: 0899069754</p>
                   @*  <p>Payment Accepted</p>
                    <img src="img/payment.png" class="img-fluid" alt=""> *@
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <title>Fruitables - Vegetable Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div>

        <!-- Spinner Start -->
        <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar start -->
        <div class="container-fluid fixed-top">
            <div class="container topbar bg-primary d-none d-lg-block">
                <div class="d-flex justify-content-between">
                    <div class="top-info ps-2">
                        <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">256 Nguyễn Văn Cừ, An Hòa, Cần Thơ</a></small>
                    </div>
                    <div class="top-link pe-2">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="text-white">Chào Mừng @Context.User.Identity.Name,</a><a asp-Controller="NhanVien" asp-action="DangXuat" class="text-white"><small class="text-white mx-2">Đăng Xuất</small></a>
                        }
                        else
                        {
                            <a asp-Controller="NhanVien" asp-action="DangNhap" class="text-white"><small class="text-white mx-2">Đăng Nhập</small></a>
                        }

                    </div>
                </div>
            </div>
            <div class="container px-0">
                <nav class="navbar navbar-light bg-white navbar-expand-xl">
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand"><h1 class="text-primary display-6">NiceNice Shop</h1></a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                        <div class="navbar-nav mx-auto">
                            <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Trang Chủ</a>

                            <a asp-controller="HangHoa" asp-action="Index" class="nav-item nav-link">Cửa Hàng</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Thành Viên</a>
                                <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                    <a asp-controller="Cart" asp-action="Index" class="dropdown-item">Giỏ Hàng</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a asp-controller="NhanVien" asp-action="Profile" class="dropdown-item">Thông tin</a>
                                        <a asp-controller="NhanVien" asp-action="DangXuat" class="dropdown-item">Đăng Xuất</a>
                                        <a asp-controller="DonHang" asp-action="index" class="dropdown-item">Quản Lý Hóa Đơn</a>
                                        <a asp-controller="DonHang" asp-action="ThongKeSanPham" class="dropdown-item">Thống Kê Sản Phẩm</a>
                                        <a asp-controller="DonHang" asp-action="ThongKeIndex" class="dropdown-item">Thống Kê Doanh Thu</a>


                                    }
                                    else
                                    {
                                        <a asp-controller="NhanVien" asp-action="DangNhap" class="dropdown-item">Đăng nhập</a>
                                    }
                                </div>
                            </div>
                           
                            @if (User.Identity.IsAuthenticated)
                            {
                                if (User.IsInRole("Admin"))
                                {
                                    <a asp-controller="Admin" asp-action="Index" class="nav-item nav-link">Quản Lý Nhân Viên</a>
                                }
                            }
                            <a asp-controller="Home" asp-action="LienHe" class="nav-item nav-link">Liên Hệ</a>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Quản Lý Sản Phẩm</a>
                                    <div class="dropdown-menu m-0 bg-secondary rounded-0">
                                        <a asp-controller="DanhMucHH" asp-action="Index" class="nav-item nav-link">Loại Hàng Hóa</a>
                                        <a asp-controller="HangHoas" asp-action="Index" class="nav-item nav-link">Danh Sách sản phẩm</a>
                                    </div>
                                </div>
                            }

                        </div>
                        <div class="d-flex m-3 me-0">
                            <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>

                            @await Component.InvokeAsync("Cart")

                            <a asp-action="Profile" asp-controller="NhanVien" title="Đăng nhập nha" class="my-auto">
                                <i class="fas fa-user fa-2x"></i>
                            </a>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->
        <!-- Modal Search Start -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input id="searchText" type="search" class="form-control p-3" placeholder="keywords" aria-describedby="seachButton">
                            <span id="seachButton" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Search End -->

        <div style="min-height:400px;" class="hero-header">
            @RenderBody()
        </div>


        @await Html.PartialAsync("_Footer")
    </div>



    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $("#seachButton").click(function () {
                let url = `/HangHoa/Search?query=` + $("#searchText").val();
                window.location.href = url;
            });
        });
    </script>
</body>
</html>

Views/Shared/_TimKiemPanel.cshtml
<form asp-action="Search" asp-controller="HangHoa">
    <div class="input-group w-100 mx-auto d-flex">
        <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1" name="query">
        <button>
            <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
        </button>
    </div>
</form>